language: java

dist: trusty
sudo: required

jdk:
  - openjdk7
  - oraclejdk8

before_script: openssl s_client -CApath /etc/ssl/certs/ -connect plugins.gradle.org:443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/gradle.crt; sudo keytool -importcert -noprompt -file /tmp/gradle.crt -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -alias root -storepass changeit

script: 
  - cd caom2; gradle --info build javadoc install checkstyleMain || exit -1; cd ..
  - cd caom2-compute; gradle --info assemble javadoc install || exit -1; cd ..
  - cd fits2caom2; gradle --info assemble javadoc || exit -1; cd ..
  - cd caom2-viz; gradle --info build || exit -1; cd ..
  # hack: switch to jdk8 for this last job
  - jdk_switcher use oraclejdk8
  - cd caom2-dm; gradle --info build initHTML xslt || exit -1; cd ..

